DROP TABLE IF EXISTS SEAT CASCADE;

CREATE TABLE IF NOT EXISTS SEAT(
    seatnum INT NOT NULL,
    barcode varchar(20) ,
    isoccupied BOOLEAN ,
    PRIMARY KEY(seatnum)
);

INSERT INTO SEAT VALUES (1,'',FALSE);
INSERT INTO SEAT VALUES (2,'',FALSE);
INSERT INTO SEAT VALUES(3,'',FALSE);
INSERT INTO SEAT VALUES(4,'',FALSE);
INSERT INTO SEAT VALUES(5,'',FALSE);
INSERT INTO SEAT VALUES(6,'',FALSE);
INSERT INTO SEAT VALUES(7,'',FALSE);
INSERT INTO SEAT VALUES(8,'',FALSE);
INSERT INTO SEAT VALUES(9,'',FALSE);
INSERT INTO SEAT VALUES(10,'',FALSE);
INSERT INTO SEAT VALUES(11,'',FALSE);
INSERT INTO SEAT VALUES(12,'',FALSE);
INSERT INTO SEAT VALUES(13,'',FALSE);
INSERT INTO SEAT VALUES(14,'',FALSE);
INSERT INTO SEAT VALUES(15,'',FALSE);
INSERT INTO SEAT VALUES(16,'',FALSE);
INSERT INTO SEAT VALUES(17,'',FALSE);
INSERT INTO SEAT VALUES(18,'',FALSE);
INSERT INTO SEAT VALUES(19,'',FALSE);
INSERT INTO SEAT VALUES(20,'',FALSE);
